name: Deploy Hugo Site

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.156.0'
          extended: true

      - name: Build site
        run: pnpm build

      - name: Deploy to Production Repo
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAT }}
          external_repository: neibaur/github.io
          publish_branch: main
          publish_dir: ./public
          cname: isaacneibaur.com
          commit_message: "Deploying latest build: ${{ github.event.head_commit.message }}"
